In [1]:
import pandas as pd
import os
import datetime
import numpy as np
import calendar

/Users/kvs25/anaconda3/lib/python3.5/site-packages/numexpr/cpuinfo.py:53: UserWarning: [Errno 2] No such file or directory: 'arch'
  stacklevel=stacklevel + 1)
/Users/kvs25/anaconda3/lib/python3.5/site-packages/numexpr/cpuinfo.py:53: UserWarning: [Errno 2] No such file or directory: 'machine'
  stacklevel=stacklevel + 1)
/Users/kvs25/anaconda3/lib/python3.5/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):

In [2]:
df = pd.read_csv('employee_compensation.csv')

In [3]:
df.head(15)

,Year Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,...,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Calendar,2013,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
1,Fiscal,2015,4,Community Health,DPH,Public Health,790.0,"SEIU - Miscellaneous, Local 1021",2600,Dietary & Food,...,52950,69169.82,755.02,4179.08,74103.92,15641.92,12499.30,5669.02,33810.24,107914.16
2,Calendar,2016,3,Human Welfare & Neighborhood Development,WOM,Department of the Status of Women,323.0,Members of Boards and Commissions,0900,Management,...,33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,6,General Administration & Finance,HRD,Human Resources,790.0,"SEIU - Miscellaneous, Local 1021",8100,Legal & Court,...,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
4,Fiscal,2015,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,15849,1102.50,0.00,0.00,1102.50,0.00,538.82,85.36,624.18,1726.68
5,Calendar,2016,2,"Public Works, Transportation & Commerce",DBI,Department of Building Inspection,790.0,"SEIU - Miscellaneous, Local 1021",1400,"Clerical, Secretarial & Steno",...,23930,80207.24,2232.53,1568.00,84007.77,15064.98,13890.29,6888.51,35843.78,119851.55
6,Fiscal,2013,2,"Public Works, Transportation & Commerce",DPW,General Services Agency - Public Works,21.0,"Prof & Tech Engineers - Miscellaneous, Local 21",5200,Professional Engineering,...,20713,146952.03,0.00,0.00,146952.03,26025.22,12801.62,10118.71,48945.55,195897.58
7,Calendar,2014,6,General Administration & Finance,ADM,General Services Agency - City Admin,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,38054,24180.00,0.00,0.00,24180.00,1490.20,8586.13,1880.37,11956.70,36136.70
8,Calendar,2015,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,790.0,"SEIU - Miscellaneous, Local 1021",2700,Housekeeping & Laundry,...,55117,56531.00,0.00,7288.42,63819.42,12650.47,12424.50,5219.56,30294.53,94113.95
9,Fiscal,2014,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,45363,10429.97,0.00,0.00,10429.97,0.00,3578.60,807.48,4386.08,14816.05
10,Calendar,2016,4,Community Health,DPH,Public Health,250.0,"SEIU - Health Workers, Local 1021",2600,Dietary & Food,...,38711,70326.45,3125.89,4723.07,78175.41,13160.74,13761.68,5986.42,32908.84,111084.25
11,Fiscal,2015,4,Community Health,DPH,Public Health,250.0,"SEIU - Health Workers, Local 1021",2600,Dietary & Food,...,10006,64899.93,4682.86,5275.82,74858.61,14963.74,12500.56,5918.94,33383.24,108241.85
12,Fiscal,2014,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",3200,Recreation,...,36851,14500.59,0.00,253.01,14753.60,0.00,5072.74,348.39,5421.13,20174.73
13,Calendar,2013,2,"Public Works, Transportation & Commerce",DPW,General Services Agency - Public Works,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,1294,5502.00,0.00,175.06,5677.06,1210.35,717.70,439.52,2367.57,8044.63
14,Calendar,2014,5,Culture & Recreation,REC,Recreation and Park Commission,261.0,"Laborers, Local 261",3400,Agriculture & Horticulture,...,23029,63978.00,17039.61,2184.23,83201.84,14287.99,13054.95,6721.63,34064.57,117266.41

In [4]:
df.columns = [c.replace(' ', '_') for c in df.columns]

In [5]:
dataset=df.groupby(['Year','Employee_Identifier']).agg({'Total_Salary':np.mean, 'Retirement':np.mean,'Health/Dental':np.mean,'Other_Benefits':np.mean,'Total_Benefits':np.mean,'Total_Compensation':np.mean})

In [6]:
dataset.head(6)

                          Health/Dental  Retirement  Total_Compensation  \
Year Employee_Identifier
2013 1                        12788.245   10669.540           84271.090
     3                         5743.665    4856.690           41103.010
     4                         1004.750       0.000            5217.670
     5                            0.000       0.000           22377.795
     6                        15689.105   27433.560          218912.525
     7                         8904.645   29400.355          235769.200

                          Total_Salary  Other_Benefits  Total_Benefits
Year Employee_Identifier
2013 1                       56300.410        4512.895       27970.680
     3                       28213.960        2288.695       12889.050
     4                        3910.200         302.720        1307.470
     5                       20739.375        1638.420        1638.420
     6                      172972.350        2817.510       45940.175
     7                      187017.435       10446.765       48751.765

In [7]:
df[df.Overtime>0.05*(df.Salaries)].Employee_Identifier.head()

11    10006
14    23029
23    20763
28    49815
31    43372
Name: Employee_Identifier, dtype: int64

In [8]:
output=df.groupby('Job_Family').agg({'Total_Benefits':np.mean, 'Total_Compensation':np.mean})

In [9]:
output.head()

                               Total_Compensation  Total_Benefits
Job_Family
Administrative & Mgmt (Unrep)       248536.124310    58804.222241
Administrative Secretarial          101995.198101    28918.649873
Administrative-DPW/PUC              156364.681576    41349.404069
Administrative-Labor & Trades       160870.450896    39922.411887
Agriculture & Horticulture           81391.643272    25407.737041

In [10]:
output['percentage']=(output.Total_Benefits/output.Total_Compensation)*100

In [11]:
output.head()

                               Total_Compensation  Total_Benefits  percentage
Job_Family
Administrative & Mgmt (Unrep)       248536.124310    58804.222241   23.660231
Administrative Secretarial          101995.198101    28918.649873   28.352952
Administrative-DPW/PUC              156364.681576    41349.404069   26.444210
Administrative-Labor & Trades       160870.450896    39922.411887   24.816498
Agriculture & Horticulture           81391.643272    25407.737041   31.216641

In [12]:
output.sort_values(by='percentage',ascending=False).head(5)

                               Total_Compensation  Total_Benefits  percentage
Job_Family
Public Service Aide                  14450.325272     5087.142130   35.204343
Housekeeping & Laundry               72612.204294    23787.827171   32.760095
Park & Zoo                           53001.043501    17359.449541   32.753034
Clerical, Secretarial & Steno        66009.821043    21394.905197   32.411700
Dietary & Food                       60295.256688    19300.787905   32.010458

In [13]:
output.to_csv(path_or_buf=os.path.join(os.getcwd(),'Q2P2.csv'))